### ISSUE TITLE
not fired the plugin

### ISSUE THREAD

**Issue by anna647** [cjpearson/cordova-plugin-keyboard#12]
hello. 

I added this plugin in my cordova project. I fired it like this 

 receivedEvent: function() {
       window.addEventListener('keyboardDidShow', function () {
            alert("tttt");
        });
    },

Was it wrong? Thanks!

**Comment by cjpearson** [comment]
That code looks correct. Could you add some more details? What iOS version are you using?

**Comment by anna647** [comment]
I‘m sorry I ignored some events are only supported in IOS. However, I tried it with my android mobile . Could you tell me how  I can use this plugin under android surrounddings,since if the native keyboard shows, the fixed header hides when i scroll the page.

**Comment by cjpearson** [comment]
Currently there's no android events in this plugin. You may want to look at something like this: https://stackoverflow.com/questions/2150078/how-to-check-visibility-of-software-keyboard-in-android

Since responding to keyboard events isn't part of Android, there are probably other ways to solve your problem. I'd recommend looking into them first.
