### ISSUE TITLE
App goes blank after installing this plugin

### ISSUE THREAD

**Issue by barocsi** [cjpearson/cordova-plugin-keyboard#18]
Hello, with iOS 8.4, cordova iOS platform 3.9.2. and WKWebView the app just goes blank white after starting with no error messages involved. The app compiles just fine without it. Any ideas to debug or try?

**Comment by cjpearson** [comment]
Are you using the wkwebview engine plugin or the telerik WKWebView plugin?

Also, what are your settings for this plugin and do you have any other plugins installed?

**Comment by PostImpatica** [comment]
Same thing happened to me.  It was working fine for the past year but all of a sudden started causing my app to crash and it took me forever to find the cause.  It's because i call `Keyboard.hide()` during launch of my app and it crashes in such a way that you can't even see anything while debugging so there was nothing to go on, it's the worst type of crash possible.  After i wrapped it in:
`if (Keyboard.isVisible) {
   Keyboard.hide();
   }`
It no longer crashes and the app works fine.  The only problem is, this command only works in iOS so you would have to detect the OS and only call this when it's running on iOS.  FYI, the other plugin that all of a sudden now crashes my iOS app is cordova-plugin-statusbar too and it started crashing my app at the exact same time.  I found [CB-10533](https://issues.apache.org/jira/browse/CB-10533) and decided to try and wrap my call to hide keyboard and statusbar (because i hide them both at the start) in a 300ms `setTimeout` function and it fixed both my statusbar problem and my keyboard plugin problem and i no longer have to wrap `Keyboard.hide()` within a `Keyboard.isVisible` test.

**Comment by pwbs** [comment]
I have something similar, but only on iPad Pro (the hardware version, not the simulator). Either the screen becomes and stays blank, or it's just wrecked (the app is displayed on about 15% of the screen, what is visible doesn't make sense, I mean the part that is visible doesn't particularly match what would have been displayed there if it were "normal")

(I'm using WKWebView...)

I'm wondering if it has something to do with the order of how plugins are added...
Notably, should the keyboard plugin be installed before or after the status bar plugin?

**Comment by pwbs** [comment]
I've done a little more investigation on my iPad Pro issue.
- if the keyboard plugin is included before the status bar plugin, the situation is worse
- if the keyboard plugin is used, I have to deactivate the "Landscape Left" orientation (which is not acceptable).
- if I don't use the keyboard plugin, I can activate all orientations.

Conclusion: for now, I'm about to generate 2 apps: one for iPhone with the keyboard plugin, and one for the iPad without the keyboard plugin.

**Comment by cjpearson** [comment]
It's definitely possible there's a conflict. Both plugins involve resizing the webview. The keyboard plugin is aware of the `StatusBarOverlaysWebView` and tries to respect it so it doesn't break the status bar plugin, but there may be issues there.

Could you add what version of the status bar plugin you're using and any plugin preferences?

**Comment by cjpearson** [comment]
Also, have you tried UIWebView?

**Comment by pwbs** [comment]
I have `<plugin name="com.phonegap.plugin.statusbar" spec="https://github.com/phonegap-build/StatusBarPlugin" />` so it's the... version at build time. Well, since it hasn't changed since Feb 26 (of 2014!), it means it's that one (https://github.com/phonegap-build/StatusBarPlugin/commit/0944be5c9f96ca0e39e0079f46ffc37894a586cd).

I have stopped using UIWebView before I started using the keyboard plugin...

**Comment by cjpearson** [comment]
That one plugin looks really old. Have you tried using https://github.com/apache/cordova-plugin-statusbar ?

**Comment by pwbs** [comment]
haha!!! Thank you so much @cjpearson, it seems to work! I can't believe it! Now I have no idea how I ended up using https://github.com/phonegap-build/StatusBarPlugin/ instead of  https://github.com/apache/cordova-plugin-statusbar ... ~_~'
(Cordova is clearly driving me nuts.)

**Comment by pwbs** [comment]
It seems that it also solves another problem that I had: on iPhone with iOS 8, the orientation was sometimes stuck in upside-down, and it could affect the whole phone when in orientation-locked mode!
