### ISSUE TITLE
Scroller issue when resizing

### ISSUE THREAD

**Issue by ccorcos** [cjpearson/cordova-plugin-keyboard#55]
I've created a minimal reproduction here:

https://github.com/ccorcos/cordova-scroller

Its just a screen with an input (1). However, when the keyboard shrinks the view, the scrollView somehow thinks that there's room to scroll and when you attempt to scroll, it shows a scrollbar on the side (2). This is really annoying when you have actual content onscreen because if you overscroll, this scrollbar turns on and you cant continue scrolling your content until the momentum dies on the scrollview.

(1)
![image](https://user-images.githubusercontent.com/1794527/28294234-83b02a36-6b0d-11e7-85be-769d851b2082.png)

(2)
![image](https://user-images.githubusercontent.com/1794527/28294227-7c8decfc-6b0d-11e7-8e03-463f421498e3.png)

**Comment by ccorcos** [comment]
Some things I've notices as well:

- this is not an issue in landscape mode
- if I got to landscape mode and back again while the keyboard is open, the scroller isnt there anymore.

**Comment by ccorcos** [comment]
- It appears the `scrollView.contentSize` isnt updated properly

**Comment by cjpearson** [comment]
Removing the iOS version check [here](https://github.com/cjpearson/cordova-plugin-keyboard/blob/master/src/ios/CDVKeyboard.m#L152) seems to solve the issue for me. The window.innerHeight bug was fixed in iOS 10, but perhaps [this method](https://github.com/WebKit/webkit/blob/fe0acad97af510662fe651e0aa58341b60ca268a/Source/WebKit/UIProcess/API/Cocoa/WKWebView.mm#L2540) is causing issues with the scroll view.

**Comment by ccorcos** [comment]
Hmm. So should we remove that in this library as well?

**Comment by cjpearson** [comment]
Merged in that change.
