### ISSUE TITLE
not firing keyboardWillHide | keyboardWillShow | keyboardDidHide | keyboardDidShow events

### ISSUE THREAD

**Issue by ashishsajwan** [cjpearson/cordova-plugin-keyboard#6]
@cjpearson  @shazron @agrieve

**Comment by cjpearson** [comment]
What device are you using? Do you have any code samples that reproduce the problem? There's not really much to go off of here.

**Comment by ashishsajwan** [comment]
i don't think device is the issue. device is latest.. 
but i'm also using full screen plugin also.. https://github.com/mesmotronic/cordova-fullscreen-plugin
while reading online i found that full screen & keyboard hiding input fields are related issue ..so i'm mentioning it here..

as far as code is concerned..
after device ready i have this 

```
window.addEventListener('keyboardDidShow', function () {
   console.log('keyboardDidShow');  // this does not logs when keyboard shows up
    // Describe your logic which will be run each time keyboard is shown.
});
```

@cjpearson

**Comment by ashishsajwan** [comment]
@cjpearson 
is this issue any how related  https://issues.apache.org/jira/browse/CB-392

**Comment by cjpearson** [comment]
It looks like you're using an Android device. None of the events have been added to the android version of the plugin yet.

**Comment by ashishsajwan** [comment]
@cjpearson OMG .. my bad.. i am using android.. & i didn't even check if this plugin supports android yet..

**Comment by ngryman** [comment]
@cjpearson Do you plan to add Android support soon? Because I have issues with keyboard behavior in fullscreen 2 years later, and I would desperately need keyboard events to react correctly.

AFAIK keyboard events aren't triggered in fullscreen, but there are workarounds. I'm not an Android specialist but here is the best resource I found on the subject: https://pspdfkit.com/blog/2016/keyboard-handling-on-android/
